cache:
  paths:
    - maven.repository/

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/maven.repository/'

stages:
  - build

branch_build:
  stage: build
  image: registry.gitlab.com/intergral/docker/build-images/maven-3:gpg-java-7
  except:
    - tags
  script:
    - mvn clean verify

tag_build:
  stage: build
  image: registry.gitlab.com/intergral/docker/build-images/maven-3:gpg-java-7
  only:
    - tags
  script:
    - mvn -s ci_settings.xml versions:set -DnewVersion=${CI_COMMIT_TAG}
    - mvn -s .ci-settings.xml clean deploy -p release-ossrh
